server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: project-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/project/**     # ????? ?????? ???????????? ? /orders
          filters:
            - RewritePath=/api/project/(?<remaining>.*), /$\{remaining} # ????????? ????
#        - id: notification-service
#          uri: http://localhost:8080
#          predicates:
#            - Path=/orders     # ????? ?????? ???????????? ? /orders
