server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://localhost:8080
          predicates:
            - Path=/orders/**     # ????? ?????? ???????????? ? /orders
          filters:
            - RewritePath=/orders/(?<remaining>.*), /orders/$\{remaining} # ????????? ????
        - id: order-ziga-service
          uri: http://localhost:8080
          predicates:
            - Path=/orders     # ????? ?????? ???????????? ? /orders
